- name: "Install Docker Engine using Ansible"
  hosts: all
  become: true
  vars:
    ansible_user: "{{ username }}"
    ansible_ssh_port: "22"
  tasks:

    - name: "Run Docker installer script"
      shell: "curl -s https://raw.githubusercontent.com/MTC0D3/devops23-dumbways-taofik/main/Stage-2/week-3/day-2/docker_installer.sh | bash"

    - name: "Ensure Docker service is started and enabled"
      systemd:
        name: docker
        state: started
        enabled: yes