- hosts: all
  become: true
  vars:
    ansible_user: "{{ newuser }}"
    ansible_ssh_port: "{{SSHport}}"

  tasks:

  - name: "Change port SSH"
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: 'Port 22'
      line: 'Port 1234'

  - name: "UFW - Allow ports for all"
    community.general.ufw:
      rule: allow
      port: "{{item}}"
    loop:
        - "1234" # SSH
        - "9100" # NodeEx
        - "8181" # Cadvisor

  - name: "UFW - Allow Other ports for appserver"
    community.general.ufw:
      rule: allow
      port: "{{item}}"
    loop:
        - "50000" # Jenkins
        - "7070" # Jenkins
        - "8080" # Grafana
        - "3000" # FE Staging
        - "5000" # BE Staging
        - "9090" # Prometheus
        - "3001" # FE Prod
        - "5001" # BE Prod
        - "5432" # PSQL
    when: inventory_hostname == 'appserver'

  - name: "UFW - Allow Other ports for gateway"
    community.general.ufw:
      rule: allow
      port: "{{item}}"
    loop:
        - "80" # HTTP Nginx
        - "443" # HTTPS Nginx
        - "5432" # PSQL
    when: inventory_hostname == 'gateway'

  - name: "UFW - Enable and deny by default"
    community.general.ufw:
      state: enabled
      default: deny

  - name: "UFW - restarted"
    ansible.builtin.systemd:
      name: ufw
      state: restarted

  - name: "reload sshd"
    ansible.builtin.systemd_service:
      name: sshd
      state: reloaded